-- MySQL Script generated by MySQL Workbench
-- Fri Aug  8 09:24:44 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TEAM2DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TEAM2DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TEAM2DB` DEFAULT CHARACTER SET utf8 ;
USE `TEAM2DB` ;

-- -----------------------------------------------------
-- Table `TEAM2DB`.`TBL_PRODUCT_CATEGORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TEAM2DB`.`TBL_PRODUCT_CATEGORY` (
  `category_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `reference_code` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TEAM2DB`.`TBL_PRODUCT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TEAM2DB`.`TBL_PRODUCT` (
  `product_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  `product_name` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  `quantity(stock)` INT NOT NULL,
  `explanation` VARCHAR(45) NOT NULL,
  `registration_date` DATETIME NOT NULL,
  `views` INT NOT NULL,
  `TBL_PRODUCTcol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `fk_TBL_PRODUCT_TBL_PRODUCT_CATEGORY1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_PRODUCT_TBL_PRODUCT_CATEGORY1`
    FOREIGN KEY (`category_id`)
    REFERENCES `TEAM2DB`.`TBL_PRODUCT_CATEGORY` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TEAM2DB`.`TBL_USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TEAM2DB`.`TBL_USER` (
  `user_id` INT NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(10) NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TEAM2DB`.`TBL_ORDER_TIME`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TEAM2DB`.`TBL_ORDER_TIME` (
  `ordertime_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `order_date` DATETIME NOT NULL,
  `processing_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ordertime_id`),
  INDEX `fk_TBL_ORDERTIME_TBL_USER_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_ORDERTIME_TBL_USER`
    FOREIGN KEY (`user_id`)
    REFERENCES `TEAM2DB`.`TBL_USER` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TEAM2DB`.`TBL_ADDRESS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TEAM2DB`.`TBL_ADDRESS` (
  `address_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `zip_code` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `detailed_address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`address_id`, `user_id`),
  INDEX `fk_TBL_ADDRESS_TBL_USER1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_ADDRESS_TBL_USER1`
    FOREIGN KEY (`user_id`)
    REFERENCES `TEAM2DB`.`TBL_USER` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TEAM2DB`.`TBL_ORDER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TEAM2DB`.`TBL_ORDER` (
  `order_id` INT NOT NULL,
  `ordertime_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `address_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  `price` INT NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_TBL_ORDER_TBL_ORDERTIME1_idx` (`ordertime_id` ASC) VISIBLE,
  INDEX `fk_TBL_ORDER_TBL_PRODUCT1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_TBL_ORDER_TBL_ADDRESS1_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_ORDER_TBL_ORDERTIME1`
    FOREIGN KEY (`ordertime_id`)
    REFERENCES `TEAM2DB`.`TBL_ORDER_TIME` (`ordertime_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_TBL_ORDER_TBL_PRODUCT1`
    FOREIGN KEY (`product_id`)
    REFERENCES `TEAM2DB`.`TBL_PRODUCT` (`product_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_TBL_ORDER_TBL_ADDRESS1`
    FOREIGN KEY (`address_id`)
    REFERENCES `TEAM2DB`.`TBL_ADDRESS` (`address_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TEAM2DB`.`TBL_SHOPPING_CART`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TEAM2DB`.`TBL_SHOPPING_CART` (
  `cart_id` INT NOT NULL,
  `TBL_USER_user_id` INT NOT NULL,
  `TBL_PRODUCT_product_id` INT NOT NULL,
  PRIMARY KEY (`cart_id`, `TBL_USER_user_id`, `TBL_PRODUCT_product_id`),
  INDEX `fk_TBL_USER_has_TBL_PRODUCT_TBL_PRODUCT1_idx` (`TBL_PRODUCT_product_id` ASC) VISIBLE,
  INDEX `fk_TBL_USER_has_TBL_PRODUCT_TBL_USER1_idx` (`TBL_USER_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_USER_has_TBL_PRODUCT_TBL_USER1`
    FOREIGN KEY (`TBL_USER_user_id`)
    REFERENCES `TEAM2DB`.`TBL_USER` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_TBL_USER_has_TBL_PRODUCT_TBL_PRODUCT1`
    FOREIGN KEY (`TBL_PRODUCT_product_id`)
    REFERENCES `TEAM2DB`.`TBL_PRODUCT` (`product_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TEAM2DB`.`TBL_COMMENTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TEAM2DB`.`TBL_COMMENTS` (
  `comment_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `content` VARCHAR(200) NOT NULL,
  `author` VARCHAR(45) NOT NULL,
  `creation_date` DATETIME NOT NULL,
  `reply_num` INT NOT NULL,
  `reply_order` INT NOT NULL,
  `reply_depth` INT NOT NULL,
  PRIMARY KEY (`comment_id`),
  INDEX `fk_TBL_COMMENTS_TBL_PRODUCT1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_COMMENTS_TBL_PRODUCT1`
    FOREIGN KEY (`product_id`)
    REFERENCES `TEAM2DB`.`TBL_PRODUCT` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TEAM2DB`.`TBL_PRODUCT_IMAGE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TEAM2DB`.`TBL_PRODUCT_IMAGE` (
  `product_imagefile_num` INT NOT NULL,
  `product_id` INT NOT NULL,
  `original_file_name` VARCHAR(45) NOT NULL,
  `file_name_to_be_saved_on_the_server` VARCHAR(45) NOT NULL,
  `file_size` VARCHAR(45) NOT NULL,
  `file_creation_date` DATETIME NOT NULL,
  `whether_to_delete_the_file` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`product_imagefile_num`),
  CONSTRAINT `fk_TBL_PRODUCT_IMAGE_TBL_PRODUCT1`
    FOREIGN KEY (`product_id`)
    REFERENCES `TEAM2DB`.`TBL_PRODUCT` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TEAM2DB`.`TBL_PAYMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TEAM2DB`.`TBL_PAYMENT` (
  `payment_id` INT NOT NULL,
  `order_id` INT NOT NULL,
  PRIMARY KEY (`payment_id`),
  INDEX `fk_TBL_PAYMENT_TBL_ORDER1_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_PAYMENT_TBL_ORDER1`
    FOREIGN KEY (`order_id`)
    REFERENCES `TEAM2DB`.`TBL_ORDER` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
